#!/usr/bin/env python
"""phase2_sweeps.py -- generate the Phase-2 IQL sweep files from ONE canonical spec.

PIPELINE.md's Phase 2 runs the same 24 sweep files in two lineages:

  stage4   seed 0, normalize_reward grid 0-7    (selects the normalization index)
  eval     seeds 1-10, the winning index         (the reported evaluation)

and requires that "nothing else changes" between them.  Hand-flipping 24 files
failed that in practice (gp_reward-priors HANDOFF §4.3.139).  Found on 2026-09-25:

  * `centre_draws` was set in NO deployment file, though §4.3.114 decided
    centring for the deployed reward too, BNN *and* MR-ensemble ("or §3.1's
    cross-family comparability breaks").  `iql_eval` defaults it to False, so
    every BNN and MR-ensemble IQL run would have deployed RAW CVaR while the BNN
    winners were SELECTED on centred CVaR: the selection/deployment mismatch
    §3.2.1 exists to prevent.
  * 16 of the 24 files were still flipped to seeds 1-10 with stage-4 indices from
    the OLD reward models.

So both lineages are generated from the spec below.  Every value a lineage
depends on is written explicitly, including ones equal to an iql_eval default
(`bnn_alpha: 0.95`), so a changed default cannot silently change a run.  The
generator checks that the two lineages differ ONLY in `seed` and
`normalize_reward`.

The oracle `tr_sweeps` are out of scope: no reward model, no stage 4, seeds 1-10
by design (PIPELINE.md).

Subcommands (run from the repo root):
    python phase2_sweeps.py check                       # audit files vs spec
    python phase2_sweeps.py stage4 [--write]            # seed-0 grid lineage
    python phase2_sweeps.py winners SWEEP_ID [...] --out winners.json
                                                        # score finished stage-4
                                                        # sweeps via iql_score
    python phase2_sweeps.py eval --winners winners.json [--write]
                                                        # seeds 1-10 lineage
    python phase2_sweeps.py --selftest
Dry-run by default; --write applies.  `eval` writes only the files whose winner
is known, so families can move to evaluation as their stage 4 finishes.
"""

import argparse
import json
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.abspath(__file__))
ENTITY, IQL_PROJECT = "champlin-university-of-arizona", "IQL-pref"
VARIANTS = ("medium_play", "medium_diverse", "large_play", "large_diverse")
STAGE4_INDICES = list(range(8))
EVAL_SEEDS = list(range(1, 11))
LINEAGE_KEYS = ("seed", "normalize_reward")    # the ONLY keys that may differ


def spec():
    """{relative_path_without_.yaml: ordered {param: value}} for all 24 files."""
    out = {}
    for v in VARIANTS:
        base = {"config_path": f"configs/offline/iql/antmaze/{v}_v2.yaml"}
        root = lambda fam: f"~/iqlpref/exp/reward_learning/antmaze_{v}_{fam}_eval"
        for kind, alpha in (("cvar", 0.95), ("mean", 0.0)):
            out[f"bnn_sweeps/sweep_antmaze_{v}_{kind}"] = dict(
                base, reward_model_root=root("bnn"), bnn_reward_model=True,
                bnn_n_samples=-1,          # all draws: label-cache key (4.3.129)
                query_length=1, bnn_alpha=alpha,
                centre_draws=True)         # item F, deployment side (4.3.114)
            out[f"ensemble_sweeps/sweep_antmaze_{v}_{kind}"] = dict(
                base, reward_model_root=root("mr"), mr_ensemble=True,
                query_length=1, mr_alpha=alpha,
                mr_burn_in=100,            # inherited, not revisited
                centre_draws=True)         # 4.3.114: MR-ensemble-CVaR centred too
        out[f"mr_sweeps/sweep_antmaze_{v}"] = dict(
            base, reward_model_root=root("mr"), query_length=1)
        out[f"pt_sweeps/sweep_antmaze_{v}"] = dict(
            base, reward_model_root=root("pt"), query_length=100)
    return out


def lineage_params(fixed, lineage, index=None):
    p = dict(fixed)
    if lineage == "stage4":
        p["seed"] = {"value": 0}
        p["normalize_reward"] = {"values": STAGE4_INDICES}
    elif lineage == "eval":
        if index not in STAGE4_INDICES:
            raise ValueError(f"winning index must be in 0-7, got {index!r}")
        p["seed"] = {"values": EVAL_SEEDS}
        p["normalize_reward"] = {"value": index}
    else:
        raise ValueError(lineage)
    return {k: (v if isinstance(v, dict) else {"value": v}) for k, v in p.items()}


def render(name, params, lineage, index=None):
    head = [
        "# GENERATED by phase2_sweeps.py -- do not hand-edit; regenerate instead",
        "# (gp_reward-priors HANDOFF §4.3.139).  Lineage: "
        + ("STAGE 4, seed 0, normalize_reward grid 0-7 (selection)."
           if lineage == "stage4" else
           f"EVALUATION, seeds 1-10, normalize_reward {index} (stage-4 winner)."),
    ]
    doc = {"project": IQL_PROJECT, "program": "algorithms/offline/iql_eval.py",
           "method": "grid", "parameters": params}
    return "\n".join(head) + "\n" + yaml.safe_dump(doc, sort_keys=False)


def flat(params):
    """{k: value-or-values} from a sweep 'parameters' block."""
    return {k: (v.get("value", v.get("values")) if isinstance(v, dict) else v)
            for k, v in (params or {}).items()}


def lineage_of(p):
    s, n = p.get("seed"), p.get("normalize_reward")
    if s == 0 and n == STAGE4_INDICES:
        return "stage4"
    if s == EVAL_SEEDS and isinstance(n, int):
        return "eval"
    return "INVALID"


def audit(name, doc, fixed):
    """(lineage, [problems]) for one existing file against the spec."""
    p = flat((doc or {}).get("parameters"))
    probs = []
    for k, v in fixed.items():
        if k not in p:
            probs.append(f"{k} missing (spec {v!r})")
        elif p[k] != v:
            probs.append(f"{k}={p[k]!r} (spec {v!r})")
    for k in p:
        if k not in fixed and k not in LINEAGE_KEYS:
            probs.append(f"{k} not in spec")
    if (doc or {}).get("program") != "algorithms/offline/iql_eval.py":
        probs.append(f"program {(doc or {}).get('program')!r}")
    return lineage_of(p), probs


def match_entry(sweep_params, sp):
    """The spec entries whose fixed params EXACTLY equal a sweep's non-lineage
    params.  Exact, not subset: MR best-model's params {config_path, root,
    query_length} are a strict subset of the MR ensemble's, so a subset match
    would file an ensemble sweep under MR best-model as well."""
    p = {k: v for k, v in flat(sweep_params).items() if k not in LINEAGE_KEYS}
    return [n for n, fixed in sp.items() if p == fixed]


GENERATED_MARK = "# GENERATED by phase2_sweeps.py"


def cmd_check(sp):
    bad = 0
    for name, fixed in sp.items():
        path = os.path.join(ROOT, name + ".yaml")
        text = open(path).read() if os.path.exists(path) else ""
        doc = yaml.safe_load(text) if text else None
        lin, probs = audit(name, doc, fixed)
        # A hand-made file cannot show WHICH stage 4 its index came from; an
        # evaluation-lineage file from before the generator carries an index
        # from the old reward models.
        if text and GENERATED_MARK not in text:
            probs = probs + ["not generated (predates phase2_sweeps.py; an eval "
                             "index here is from an unknown stage 4)"]
        bad += bool(probs) or lin == "INVALID"
        print(f"  {name:48s} {lin:8s} {'OK' if not probs else '; '.join(probs)}")
    print(f"\n  {len(sp) - bad}/{len(sp)} files match the spec")
    return 0 if not bad else 1


def write_all(sp, lineage, winners, do_write):
    n = 0
    for name, fixed in sp.items():
        idx = None
        if lineage == "eval":
            if name not in winners:
                print(f"  {name:48s} SKIP (no stage-4 winner yet)")
                continue
            idx = winners[name]
        params = lineage_params(fixed, lineage, idx)
        text = render(name, params, lineage, idx)
        back = yaml.safe_load(text)
        # audit() requires every non-lineage key to equal the spec and forbids
        # extras -- which IS the invariant that the two lineages differ only in
        # seed/normalize_reward, since both are the same spec plus those two.
        lin, probs = audit(name, back, fixed)
        assert lin == lineage and not probs, (name, lin, probs)
        path = os.path.join(ROOT, name + ".yaml")
        old = open(path).read() if os.path.exists(path) else ""
        change = "unchanged" if old == text else "CHANGED"
        if do_write and old != text:
            open(path, "w").write(text)
        n += 1
        print(f"  {name:48s} {lineage}{'' if idx is None else f' idx {idx}'}  "
              f"{change}{' (written)' if do_write and old != text else ''}")
    print(f"\n  {n} file(s) {'written' if do_write else 'checked (dry run; --write to apply)'}")
    return 0


def cmd_winners(sweep_ids, sp, out):
    sys.path.insert(0, os.path.join(ROOT, "results"))
    import iql_score
    import wandb
    api = wandb.Api(timeout=120)
    winners = json.load(open(out)) if out and os.path.exists(out) else {}
    for sid in sweep_ids:
        path = sid if sid.count("/") == 2 else f"{ENTITY}/{IQL_PROJECT}/{sid}"
        sw = api.sweep(path)
        hits = match_entry(sw.config.get("parameters"), sp)
        if len(hits) != 1:
            sys.exit(f"{sid}: matches {len(hits)} spec entries {hits} -- "
                     "not a stage-4 sweep generated from this spec?")
        if lineage_of(flat(sw.config.get("parameters"))) != "stage4":
            sys.exit(f"{sid}: not a stage-4 (seed 0, grid 0-7) sweep")
        scored = []
        for r in sw.runs:
            s = iql_score.score_run(r)
            s["normalize_reward"] = (r.config or {}).get("normalize_reward")
            scored.append(s)
        win, table = iql_score.select_normalization(scored)
        winners[hits[0]] = int(win)
        print(f"  {hits[0]:48s} winner idx {win}  ({table[0]['score']:.4f}; "
              f"runner-up idx {table[1]['normalize_reward']} {table[1]['score']:.4f})")
    if out:
        json.dump(winners, open(out, "w"), indent=2, sort_keys=True)
        print(f"\n  {len(winners)} winner(s) in {out}")
    return 0


def selftest():
    sp = spec()
    assert len(sp) == 24, len(sp)
    assert sum(1 for n in sp if n.startswith("bnn_")) == 8
    for n, f in sp.items():
        if n.startswith(("bnn_", "ensemble_")):
            assert f["centre_draws"] is True, n            # item F, both families
        if n.startswith("bnn_"):
            assert f["bnn_n_samples"] == -1, n
            assert f["bnn_alpha"] == (0.95 if n.endswith("cvar") else 0.0), n
    # lineages differ only in seed/normalize_reward
    f = sp["bnn_sweeps/sweep_antmaze_large_play_cvar"]
    a, b = flat(lineage_params(f, "stage4")), flat(lineage_params(f, "eval", 3))
    assert {k for k in a if a[k] != b[k]} == {"seed", "normalize_reward"}
    assert a["seed"] == 0 and a["normalize_reward"] == list(range(8))
    assert b["seed"] == list(range(1, 11)) and b["normalize_reward"] == 3
    # render round-trips and audits clean
    t = render("x", lineage_params(f, "eval", 3), "eval", 3)
    lin, probs = audit("x", yaml.safe_load(t), f)
    assert lin == "eval" and not probs, (lin, probs)
    # the pre-fix file (no centre_draws, no bnn_alpha) must FAIL the audit
    old = {"program": "algorithms/offline/iql_eval.py", "parameters": {
        k: {"value": v} for k, v in f.items() if k not in ("centre_draws", "bnn_alpha")}}
    old["parameters"].update(seed={"value": 0}, normalize_reward={"values": list(range(8))})
    lin, probs = audit("x", old, f)
    assert any("centre_draws missing" in p for p in probs), probs
    # a sweep maps to exactly one entry; mean and cvar are distinguishable
    hits = match_entry(lineage_params(f, "stage4"), sp)
    assert hits == ["bnn_sweeps/sweep_antmaze_large_play_cvar"], hits
    assert match_entry(lineage_params(sp["ensemble_sweeps/sweep_antmaze_medium_play_mean"],
                                      "stage4"), sp) == \
        ["ensemble_sweeps/sweep_antmaze_medium_play_mean"]
    # MR best-model and MR ensemble share a root but must not collide
    assert match_entry(lineage_params(sp["mr_sweeps/sweep_antmaze_medium_play"],
                                      "stage4"), sp) == ["mr_sweeps/sweep_antmaze_medium_play"]
    try:
        lineage_params(f, "eval", 9)
        raise AssertionError("accepted index 9")
    except ValueError:
        pass
    print("selftest OK")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", nargs="?", choices=("check", "stage4", "eval", "winners"))
    ap.add_argument("sweep_ids", nargs="*")
    ap.add_argument("--winners", default=None, help="JSON {file: index} for eval")
    ap.add_argument("--out", default="phase2_winners.json")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    sp = spec()
    if a.cmd == "check":
        return cmd_check(sp)
    if a.cmd == "stage4":
        return write_all(sp, "stage4", {}, a.write)
    if a.cmd == "eval":
        if not a.winners:
            ap.error("eval needs --winners winners.json (from `winners`)")
        return write_all(sp, "eval", json.load(open(a.winners)), a.write)
    if a.cmd == "winners":
        if not a.sweep_ids:
            ap.error("winners needs the stage-4 sweep ids launch.sh printed")
        return cmd_winners(a.sweep_ids, sp, a.out)
    ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
