actor_dropout: 0.1
actor_lr: 0.0003
batch_size: 256
beta: 3.0
buffer_size: 1000000
checkpoints_path: null
reward_model_path: ./gp_reward-priors/exp/reward_learning/pen/br-pen-f86cc2a5
dataset_id: D4RL/pen/cloned-v2
eval_episodes: 10
eval_every: 5000
eval_seed: 0
gamma: 0.99
group: iql-pref-pen-cloned-v1-multiseed-v0
iql_deterministic: false
iql_tau: 0.8
name: iql-br
normalize_reward: false
normalize_state: true
project: IQL-pref
qf_lr: 0.0003
tau: 0.005
train_seed: 0
update_steps: 1000000
vf_lr: 0.0003
reward_type: 0